application: wowtaria
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: annotaria/static/
- url: /.*
  script: main.app  # a WSGI application in the main module's global scope

libraries:
- name: MySQLdb
  version: "1.2.4"
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: 'Wowtaria.settings'